### ISSUE TITLE
1.21.2/1.21.3 Tracking

### ISSUE THREAD

**Issue by MrTronMan** [MrTronMan/Amend#13]
# 1.21.3 Tracking
This will help keep track for you of Amend's 1.21.3 release.

- [X] Waiting on Spigot to release buid
- [x] Waiting on Paper to release first build (even experimental builds)
- [x] Waiting on Purpur to release first build after Paper's first builds (even experimental builds)
- [x] Adjust API URLs to follow Paper's new API for Downloads
- [x] Build into API 1.21.3
- [x] Test Amend and Verify
- [x] Add Version to Website and other third party plugin distributors

You can also use this link to track Paper's tasks as well, if you want specificity: 
https://github.com/PaperMC/Paper/issues/11511

**Comment by qtqgyt** [comment]
1.21.2...?

**Comment by MrTronMan** [comment]
> 1.21.2...?

Minecraft has already released a hot fix (1.21.3) to fix major bugs with resource packs and realms, 1.21.2 & 1.21.3 are the same protocol version which means they can be used with each other but 1.21.3 is what majority of servers (paper and purpur) will release as I believe. If I am mistaken then I will tweak it for 1.21.2 instead.

**Comment by qtqgyt** [comment]
Sorry didnt see that at the time of posting this.

**Comment by MrTronMan** [comment]
No worries, if you do then I thank you for using my plugin!

**Comment by Komas19-new** [comment]
paper experimental builds just released

**Comment by MrTronMan** [comment]
ty, i did not check yesterday!

**Comment by Komas19-new** [comment]
purpur released an experimental build... and a new website

**Comment by MrTronMan** [comment]
ty very much! have not been online recently, will release today!

**Comment by MrTronMan** [comment]
Amend has released, if anyone encounters issues feel free to open an issue! Thank you to all who helped keep me on track with knowing when Purpur and Paper released their builds.
