### ISSUE TITLE
1.21.4 Tracking 

### ISSUE THREAD

**Issue by MrTronMan** [MrTronMan/Amend#14]
# 1.21.4 Tracking
This will help keep track for you of Amend's 1.21.4 release.

- [x] Waiting on Spigot to release buid
- [x] Waiting on Paper to release first build (even experimental builds)
- [x] Waiting on Purpur to release first build after Paper's first builds (even experimental builds)
- [x] Adjust API URLs to follow Paper's new API for Downloads
- [x] Build into API 1.21.4
- [x] Test Amend and Verify
- [x] Add Version to Website and other third party plugin distributors

You can also use this link to track Paper's tasks as well, if you want specificity: 
https://github.com/PaperMC/Paper/issues/11704

**Comment by MrTronMan** [comment]
The builds for Amend are out now!!

WARNING: PURPUR AND PAPER ARE STILL IN BETA AND CAN CAUSE ISSUES. PLEASE USE THEIR BETAS AT YOUR OWN RISK.
